### ISSUE TITLE
Remove support for Python 3.9

### ISSUE THREAD

**Issue by jsignell** [TomNicholas/VirtualiZarr#111]
According to NEP 29, removing Python 3.9 has been allowed since April 5th, 2024. I just ran into this on #110 because I am partial to 3.10+ type unions 🤓 

https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table

**Comment by TomNicholas** [comment]
I support this too! I also don't like having to write `Union[` everywhere. 😆
