### ISSUE TITLE
Required changes in xarray to avoid creating indexes

### ISSUE THREAD

**Issue by TomNicholas** [TomNicholas/VirtualiZarr#14]
~~Everything mentioned in this issue https://github.com/pydata/xarray/issues/8699 also needs to be done for this library to work.~~

EDIT: This is a lie, see comment below

**Comment by TomNicholas** [comment]
The above isn't quite true. We should distinguish here between

1) Things that are needed to support creating xarray Datasets with no indexes, which we want in order to avoid loading any data. This means https://github.com/pydata/xarray/issues/8704 so we can pass `indexes={}` to xarray constructors. This would be useful because a concatenation problem where we know in advance the ordering of all datasets (i.e. `combine_nested` rather than `combine_by_coords`) doesn't require creating any indexes. I'll track that in this issue.

2) Things that are needed to support using the xarray backend entrypoint system to open datasets from disk as `ManifestArray`-backed Variables just by passing a keyword arg to `open_dataset`/`open_mfdataset`. This requires dodging some internal array wrapping that occurs in the depths of xarray's backend machinery.

**Comment by TomNicholas** [comment]
See also #44

**Comment by TomNicholas** [comment]
1. Also requires https://github.com/pydata/xarray/issues/8871 to be solved upstream in xarray. That completes the list for (1) I believe.

**Comment by TomNicholas** [comment]
I made a branch on my fork of xarray, which contains the (unmerged upstream) PRs https://github.com/pydata/xarray/pull/8711, https://github.com/pydata/xarray/pull/8714 and https://github.com/pydata/xarray/pull/8872. All three of these are needed for (1).

**Comment by TomNicholas** [comment]
Actually now the only unmerged PR to xarray that is needed for (1) is https://github.com/pydata/xarray/pull/8872, so I've changed the VirtualiZarr build to only point to that in https://github.com/TomNicholas/VirtualiZarr/commit/08774f7a54be5d4435f4af1f076f7479815297e0.

**Comment by jsignell** [comment]
Is this now closable? 👀

**Comment by TomNicholas** [comment]
Yes I think so! But note that additional changes in xarray would be required to support #18 .
