### ISSUE TITLE
Docs build as a test in the CI

### ISSUE THREAD

**Issue by TomNicholas** [TomNicholas/VirtualiZarr#49]
It would be nice if the docs build was present as a test on each PR, so you can see what the docs will look like after the PR / if the build succeeded.

Where would this need to go @norlandrhagen ?

**Comment by TomNicholas** [comment]
I'm also a bit confused on how its supposed to take for a change to `main` to be reflected in the public docs build, or whether I need to release or something first?

**Comment by norlandrhagen** [comment]
I think we can close this after our RTD work. New PR's have docs builds now included. see: https://github.com/TomNicholas/VirtualiZarr/pull/53
