### ISSUE TITLE
Inconsistency with CI conda environment and test dependencies results in tests failing in local pip install.

### ISSUE THREAD

**Issue by sharkinsspatial** [TomNicholas/VirtualiZarr#88]
https://github.com/TomNicholas/VirtualiZarr/pull/64/commits/5952cda0fd02e6a29a140b20997a45f52aa9d192 removed `netCDF4` from test dependencies.  As per the `xarray.to_netcdf` docs

>The default format is NETCDF4 if you are saving a file to disk and have the netCDF4-python library available. Otherwise, xarray falls back to using scipy to write netCDF files and defaults to the NETCDF3_64BIT format (scipy does not support netCDF4).

So without this dependency, the [netcdf4 file](https://github.com/TomNicholas/VirtualiZarr/blob/main/virtualizarr/tests/test_kerchunk.py#L160) in `test_kerchunk` will actually fallback to creating a `NETCDF3_64BIT` file causing [assert failure](https://github.com/TomNicholas/VirtualiZarr/blob/main/virtualizarr/tests/test_kerchunk.py#L162).

The CI [environment.yaml](https://github.com/TomNicholas/VirtualiZarr/blob/main/ci/environment.yml#L10) still contains the dependency so tests pass in the CI environment.

**Comment by sharkinsspatial** [comment]
@TomNicholas I'll submit a PR for this, just wanted to make a note quickly as it was blocking my local tests.

**Comment by TomNicholas** [comment]
Was this closed by #90?
