### ISSUE TITLE
Run CI w/o conda env file

### ISSUE THREAD

**Issue by norlandrhagen** [TomNicholas/VirtualiZarr#89]
Wondering if we should run the CI tests from an environment installed from the pyproject.toml file. This would help prevent issues like: https://github.com/TomNicholas/VirtualiZarr/issues/88 in the future.

**Comment by norlandrhagen** [comment]
Companion PR: https://github.com/TomNicholas/VirtualiZarr/pull/90

**Comment by TomNicholas** [comment]
This was closed by #90 right?
