### ISSUE TITLE
Add isort / black to pre-commit?

### ISSUE THREAD

**Issue by TomNicholas** [TomNicholas/VirtualiZarr#96]
I noticed that although we run ruff on pre-commit, a lot of the time it doesn't tidy up things that it could do, e.g. untidily-placed `import` statements. We probably need to add more pre-commit tools / configure ruff.

**Comment by dcherian** [comment]
ruff requires you to opt-in to a bunch of rules.

**Comment by jbusecke** [comment]
What @dcherian said. I have been using [this](https://github.com/jbusecke/pangeo-forge-esgf/blob/3f4a8e9de383a62a20cb562dc1287c1a665f3f22/.pre-commit-config.yaml#L11-L19) recently with pre-commit.ci and it works really nicely!
Shall I make a PR?

**Comment by jbusecke** [comment]
I went ahead and added #98. Let me know if you want some of the configs to change.
